import {
  LayoutDashboard,
  Settings,
  ScrollText,
  ShoppingCart,
  Shirt,
  Users,
  Warehouse,
  PieChart,
  Layers,
  Ruler,
  TrendingUp,
  AlertTriangle,
  Hash,
  Box,
  Building2,
  Receipt,
  Wallet,
  CreditCard,
  ShieldCheck,
  UserCog
} from "lucide-react";

export const allNavigation = [
  { name: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { name: "POS Terminal", href: "/pos", icon: ShoppingCart },
  { name: "Products", href: "/products", icon: Shirt },
  { name: "Categories", href: "/categories", icon: Layers },
  { name: "Sizes", href: "/sizes", icon: Ruler },
  { name: "Bank Accounts", href: "/masters/banks", icon: Building2 },
  { name: "Expense Master", href: "/masters/expense-categories", icon: Layers },
  { name: "Expenses", href: "/pos/expenses", icon: Receipt },
  { name: "Customer Khata", href: "/pos/ledger", icon: Wallet },
  { name: "Customers", href: "/customers", icon: Users },
  { name: "Inventory", href: "/inventory", icon: Warehouse },
  { name: "Bill Profit", href: "/reports/bill-profit", icon: ScrollText },
  { name: "Business P&L", href: "/reports/pnl", icon: PieChart },
  { name: "Item Performance", href: "/reports/item-profit", icon: TrendingUp },
  { name: "Stock Valuation", href: "/reports/stock-summary", icon: Warehouse },
  { name: "Low Stock", href: "/reports/low-stock", icon: AlertTriangle },
  { name: "Category Report", href: "/reports/category", icon: Layers },
  { name: "Batch Tracking", href: "/reports/batch", icon: Box },
  { name: "Serial Tracking", href: "/reports/serial", icon: Hash },
  { name: "Invoice Center", href: "/invoices", icon: ScrollText },
  { name: "User Roles", href: "/masters/roles", icon: ShieldCheck, roles: ["tenant", "super_admin"] },
  { name: "Employee Management", href: "/settings/employees", icon: UserCog, roles: ["tenant", "super_admin"] },
  { name: "Global Customers", href: "/admin/customers", icon: Users, roles: ["super_admin"] },
];

export const allBottomNav = [
  { name: "Settings", href: "/settings", icon: Settings },
];
